# Generated by Django 3.2.5 on 2021-08-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='Products',
        ),
    ]
